# Generated by Django 4.0 on 2023-03-08 06:11

import ckeditor.fields
import ckeditor_uploader.fields
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimAndObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_listing', models.TextField(blank=True, help_text='Short Listing', max_length=200)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(blank=True, max_length=35)),
                ('short_note', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('file', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(blank=True, max_length=35)),
                ('short_note', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('hero_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_strategy', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='OurTargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_audience', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('is_visible_in_index_page', models.BooleanField(default=True, verbose_name='Index page visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do_icon', to='core.icon')),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do_item', to='core.whatwedo')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-are')),
                ('short_description', ckeditor.fields.RichTextField(help_text='short description for index page', max_length=700)),
                ('long_description', ckeditor.fields.RichTextField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='what_we_are', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('is_visible_in_index_page', models.BooleanField(default=True, verbose_name='Index page visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_item_icon', to='core.icon')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_item', to='core.ourtargetaudience')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('display_in_index', models.BooleanField(default=True, help_text='Format:True: Will display in index page or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_item_icon', to='core.icon')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_item', to='core.ourstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=250)),
                ('person_status', models.CharField(choices=[('M', 'Managing Body'), ('P', 'Parmanent Speaker'), ('G', 'Guest Speaker')], max_length=20)),
                ('avatar', models.ImageField(default='default/default_avatar.jpg', help_text='Supported Image Format: jpg and png. Max file size is 10mb.', upload_to=core.models.ResourcePerson.get_resource_person_avatar_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), core.models.validate_resource_person_avatar_file_size])),
                ('organization_name', models.CharField(blank=True, help_text='Any other organization or university name where the person is associated or studied', max_length=200)),
                ('organization_designation', models.CharField(blank=True, help_text='His/Her designation in that organization', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='resource person bio or details', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, help_text='User who has created or edit the form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Resource Person',
                'verbose_name_plural': 'Resource Persons',
            },
        ),
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/preamble')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Preamble short description for index page', max_length=700)),
                ('long_description', ckeditor.fields.RichTextField(blank=True, help_text='Preamble detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preamble', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='OurVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image1', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image2', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image3', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Short Description', max_length=600)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_vision', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Short Description', max_length=700)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_mission', to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=200)),
                ('email', models.EmailField(help_text='Your email address', max_length=60, verbose_name='email')),
                ('contact_number', models.CharField(blank=True, help_text='Supported Formats: +8801757551134, 8801757871165 or 01715604232', max_length=14, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+88)?01[3-9]\\d{8}$', message='Contact number must be entered in following formats: +8801757551134, 8801857871165 or 01915604232')])),
                ('details', models.TextField(help_text='Tell us about your thoughts', max_length=500)),
                ('checked', models.BooleanField(default=False, help_text='format:true means you have checked the contact message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, help_text='User who has received the message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='AimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=255)),
                ('aim_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aim_item', to='core.aimandobjectives')),
            ],
        ),
        migrations.AddField(
            model_name='aimandobjectives',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aim_objectives', to='core.herosection'),
        ),
    ]
