# Generated by Django 4.0 on 2023-02-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=200)),
                ('email', models.EmailField(help_text='Your email address', max_length=60, verbose_name='email')),
                ('details', models.TextField(help_text='Tell us about your thoughts', max_length=500)),
                ('checked', models.BooleanField(default=False, help_text='format:true means you have checked the contact message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(help_text='User who has received the message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
