# Generated by Django 4.0 on 2023-02-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who has received the message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
    ]
