# Generated by Django 4.0 on 2023-02-26 20:48

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('core', '0002_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=250)),
                ('person_status', models.CharField(choices=[('M', 'Managing Body'), ('F', 'Parmanent Speaker'), ('G', 'Guest Speaker')], max_length=20)),
                ('avatar', models.ImageField(default='default/default_avatar.jpg', help_text='Supported Image Format: jpg and png. Max file size is 10mb.', upload_to=core.models.ResourcePerson.get_resource_person_avatar_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), core.models.validate_resource_person_avatar_file_size])),
                ('organization_name', models.CharField(blank=True, help_text='Any other organization or university name where the person is associated or studied', max_length=200)),
                ('organization_designation', models.CharField(blank=True, help_text='His/Her designation in that organization', max_length=200)),
                ('description', models.TextField(help_text='resource person bio or details', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, help_text='User who has created or edit the form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Resource Person',
                'verbose_name_plural': 'Resource Persons',
            },
        ),
    ]
