# Generated by Django 4.0 on 2023-03-01 20:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_resourceperson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(blank=True, max_length=35)),
                ('short_note', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(blank=True, max_length=35)),
                ('short_note', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListAndCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_or_card_icon', to='core.icon')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do_item', to='core.listandcarditem')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-are')),
                ('short_description', ckeditor.fields.RichTextField(help_text='short description for index page', max_length=300)),
                ('long_description', ckeditor.fields.RichTextField(help_text='Detail description for single page', max_length=1000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_audience_item', to='core.listandcarditem')),
            ],
        ),
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/preamble')),
                ('short_description', ckeditor.fields.RichTextField(help_text='Preamble short description for index page', max_length=300)),
                ('long_description', ckeditor.fields.RichTextField(help_text='Preamble detail description for single page', max_length=1000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='OurVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image1', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image2', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image3', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_description', models.TextField(help_text='Short Description', max_length=200)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Detail description for single page', max_length=1000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='OurStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
                ('strategy_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_item', to='core.listandcarditem')),
            ],
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('index_page_image1', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image2', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('index_page_image3', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_description', models.TextField(help_text='Short Description', max_length=200)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Detail description for single page', max_length=1000)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='AimAndObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_image', models.ImageField(default='default/default_avatar.jpg', upload_to='pages/what-we-do')),
                ('short_listing', models.TextField(blank=True, help_text='Short Listing', max_length=200)),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aim_item', to='core.aimitem')),
                ('hero_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.herosection')),
            ],
        ),
    ]
