# Generated by Django 4.0 on 2023-03-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aimitem_herosection_icon_indexslider_listandcarditem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more', models.BooleanField(default=False, help_text='represents read more button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_audience_item', to='core.listandcarditem')),
            ],
        ),
        migrations.RemoveField(
            model_name='aimandobjectives',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='ourstrategy',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='ourvision',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='preamble',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='whatweare',
            name='hero_section',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='hero_section',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ourstrategy'),
        ),
        migrations.DeleteModel(
            name='TargetAudience',
        ),
    ]
