# Generated by Django 4.0 on 2023-03-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ourtargetaudience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='hero_section',
        ),
        migrations.AddField(
            model_name='herosection',
            name='pramble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.preamble'),
        ),
    ]
