# Generated by Django 4.0 on 2023-03-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_herosection_hero_section_herosection_pramble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='pramble',
        ),
        migrations.AddField(
            model_name='aimandobjectives',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aim_objectives', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='page',
            field=models.CharField(choices=[('PREAMBLE', 'PREAMBLE'), ('WHAT-WE-ARE', 'WHAT-WE-ARE'), ('WHAT-WE-DO', 'WHAT-WE-DO'), ('OUR-VISION', 'OUR-VISION'), ('OUR-MISSION', 'OUR-MISSION'), ('OUR-TARGET-AUDIENCE', 'OUR-TARGET-AUDIENCE'), ('OUR-AIM-OBJECTIVES', 'OUR-AIM-OBJECTIVES'), ('OUR-STRATEGY', 'OUR-STRATEGY')], default='PREAMBLE', max_length=30),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_mission', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='ourstrategy',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_strategy', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='ourtargetaudience',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_audience', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='ourvision',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_vision', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='preamble',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preamble', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='whatweare',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='what_we_are', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do', to='core.herosection'),
        ),
    ]
