# Generated by Django 4.0 on 2023-03-02 07:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_herosection_pramble_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_item_icon', to='core.icon')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_item_icon', to='core.icon')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('short_note', models.TextField(help_text='Short Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do_icon', to='core.icon')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourstrategy',
            name='strategy_item',
        ),
        migrations.RemoveField(
            model_name='ourtargetaudience',
            name='target_item',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='what_we_do',
        ),
        migrations.AddField(
            model_name='aimandobjectives',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=1000),
        ),
        migrations.AddField(
            model_name='ourstrategy',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=1000),
        ),
        migrations.AddField(
            model_name='ourtargetaudience',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=1000),
        ),
        migrations.DeleteModel(
            name='ListAndCardItem',
        ),
        migrations.AddField(
            model_name='whatwedocarditem',
            name='what_we_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='what_we_do_item', to='core.whatwedo'),
        ),
        migrations.AddField(
            model_name='targetcarditem',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_item', to='core.ourtargetaudience'),
        ),
        migrations.AddField(
            model_name='strategycarditem',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_item', to='core.ourstrategy'),
        ),
    ]
