# Generated by Django 4.0 on 2023-03-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_strategycarditem_targetcarditem_whatwedocarditem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimandobjectives',
            name='aim',
        ),
        migrations.AddField(
            model_name='aimitem',
            name='aim_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aim_item', to='core.aimandobjectives'),
        ),
    ]
