# Generated by Django 4.0 on 2023-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_aimandobjectives_aim_aimitem_aim_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycarditem',
            name='display_in_index',
            field=models.BooleanField(default=True, help_text='Format:True: Will display in index page or not'),
        ),
    ]
