# Generated by Django 4.0 on 2023-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_strategycarditem_display_in_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcarditem',
            name='is_visible_in_index_page',
            field=models.BooleanField(default=True, verbose_name='Index page visibility'),
        ),
    ]
