# Generated by Django 4.0 on 2023-03-05 10:00

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_targetcarditem_is_visible_in_index_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimandobjectives',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='short_description',
            field=models.TextField(help_text='Short Description', max_length=700),
        ),
        migrations.AlterField(
            model_name='ourstrategy',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourtargetaudience',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourvision',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourvision',
            name='short_description',
            field=models.TextField(help_text='Short Description', max_length=600),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='long_description',
            field=ckeditor.fields.RichTextField(help_text='Preamble detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Preamble short description for index page', max_length=700),
        ),
        migrations.AlterField(
            model_name='whatweare',
            name='long_description',
            field=ckeditor.fields.RichTextField(help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='whatweare',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='short description for index page', max_length=700),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
    ]
