# Generated by Django 4.0 on 2023-03-05 10:03

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aimandobjectives_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourmission',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ourvision',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Preamble detail description for single page', max_length=3000),
        ),
        migrations.AlterField(
            model_name='whatweare',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detail description for single page', max_length=3000),
        ),
    ]
