# Generated by Django 4.0 on 2023-03-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ourmission_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourmission',
            old_name='index_page_image1',
            new_name='index_page_side_image',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='index_page_image2',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='index_page_image3',
        ),
    ]
