# Generated by Django 4.0 on 2023-03-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_index_page_image1_ourmission_index_page_side_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategycarditem',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_item', to='core.ourstrategy'),
        ),
    ]
