# Generated by Django 4.0 on 2023-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_strategycarditem_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedocarditem',
            name='is_visible_in_index_page',
            field=models.BooleanField(default=True, verbose_name='Index page visibility'),
        ),
    ]
