# Generated by Django 4.0 on 2023-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_whatwedocarditem_is_visible_in_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
