# Generated by Django 4.0 on 2023-03-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ourmission_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourmission',
            old_name='index_page_side_image',
            new_name='index_page_image',
        ),
    ]
