# Generated by Django 4.0 on 2023-03-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_index_page_side_image_ourmission_index_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstrategy',
            name='hero_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='our_strategy', to='core.herosection'),
        ),
    ]
