# Generated by Django 4.0 on 2023-03-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_ourstrategy_hero_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='herosection',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page_hero_section', to='core.page'),
        ),
    ]
