# Generated by Django 4.0 on 2023-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_herosection_link_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='page',
        ),
        migrations.AddField(
            model_name='herosection',
            name='page_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
