# Generated by Django 4.0 on 2023-03-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_herosection_page_herosection_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
