# Generated by Django 4.0 on 2023-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_herosection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='page_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(),
        ),
    ]
