# Generated by Django 4.0 on 2023-03-06 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_resourceperson_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Supported Formats: +8801757551134, 8801757871165 or 01715604232', max_length=14, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+88)?01[3-9]\\d{8}$', message='Contact number must be entered in following formats: +8801757551134, 8801857871165 or 01915604232')]),
        ),
    ]
