# Generated by Django 4.0 on 2023-02-27 19:35

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_account_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News or Event Title', max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='course safe URL')),
                ('title_intro', models.TextField(help_text='Small description will be displayed in list card.', max_length=300)),
                ('image_thumbnail', imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in list view card', upload_to=newsletter.models.Event.get_image_thumbnail_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), newsletter.models.validate_image_thumbnail_file_size])),
                ('content_type', models.CharField(choices=[('Link', 'Link'), ('Blog', 'Blog')], max_length=20)),
                ('event_status', models.CharField(choices=[('Current', 'Current'), ('Upcoming', 'Upcoming')], max_length=20)),
                ('event_url', models.URLField(blank=True, help_text='Event Outside URl. If you fill this, keep description empty.', max_length=255)),
                ('event_date', models.DateTimeField(blank=True, help_text='Current or upcoming event date', null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Maximum 3000 characters. Event or News Blog Description.If you fill this, keep event url empty.', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(help_text='User who create or edit the news or event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
