# Generated by Django 4.0 on 2023-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Slug should be unique. Slug will be automatically created from title. No need to edit slug field and keep the title unique to create unique slug.', max_length=200, unique=True, verbose_name='course safe URL'),
        ),
    ]
