# Generated by Django 4.0 on 2023-02-27 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program or event name', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in gallery', upload_to=newsletter.models.Gallery.get_image_thumbnail_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), newsletter.models.validate_image_thumbnail_file_size])),
                ('caption', models.CharField(default='galllery image', help_text='Image caption', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_gallery', to='newsletter.program')),
            ],
        ),
    ]
