# Generated by Django 4.0 on 2023-03-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_program_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue', max_length=100),
        ),
    ]
