# Generated by Django 4.0 on 2023-03-07 18:07

import django.core.validators
from django.db import migrations
import imagekit.models.fields
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_event_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in gallery', upload_to=newsletter.models.Gallery.get_image_thumbnail_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), newsletter.models.validate_image_thumbnail_file_size]),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in gallery', upload_to=newsletter.models.Gallery.get_image_thumbnail_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), newsletter.models.validate_image_thumbnail_file_size]),
        ),
    ]
