# Generated by Django 4.0 on 2023-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_month', models.CharField(max_length=20)),
                ('current_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_month', models.CharField(max_length=20)),
                ('current_year', models.CharField(max_length=4)),
            ],
        ),
    ]
