# Generated by Django 4.0 on 2023-03-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_month', models.CharField(max_length=20)),
                ('current_year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Admission Num/Month',
                'verbose_name_plural': 'Admission Num/Month',
            },
        ),
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_month', models.CharField(max_length=20)),
                ('current_year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Registration Num/Month',
                'verbose_name_plural': 'Registration Num/Month',
            },
        ),
        migrations.CreateModel(
            name='StudentsPerCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_year', models.CharField(blank=True, max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_per_company_info', to='student_forum.company')),
            ],
            options={
                'verbose_name': 'No. of Students/Company',
                'verbose_name_plural': 'No. of Students/Company',
            },
        ),
    ]
