# Generated by Django 4.0 on 2023-02-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0014_delete_university_alter_studentfeedback_university'),
        ('resume', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissioninfo',
            options={'verbose_name': 'Admission Num/Month', 'verbose_name_plural': 'Admission Num/Month'},
        ),
        migrations.AlterModelOptions(
            name='registrationinfo',
            options={'verbose_name': 'Registration Num/Month', 'verbose_name_plural': 'Registration Num/Month'},
        ),
        migrations.CreateModel(
            name='StudentsPerUniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_per_info', to='resume.university')),
            ],
            options={
                'verbose_name': 'No. of Students/University',
                'verbose_name_plural': 'No. of Students/University',
            },
        ),
        migrations.CreateModel(
            name='StudentsPerCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(default=0)),
                ('current_year', models.CharField(blank=True, max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_per_company_info', to='student_forum.company')),
            ],
            options={
                'verbose_name': 'No. of Students/Company',
                'verbose_name_plural': 'No. of Students/Company',
            },
        ),
    ]
