# Generated by Django 4.0 on 2023-03-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_admissioninfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsperuniversityinfo',
            name='university',
        ),
    ]
