# Generated by Django 4.0 on 2023-03-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_studentsperuniversityinfo_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsPerUniversityInfo',
        ),
    ]
