# Generated by Django 4.0 on 2023-02-25 18:00

import accounts.models
import accounts.validators
import django.core.validators
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_avatar.jpg', upload_to=accounts.models.Account.get_account_avatar_file_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png']), accounts.validators.validate_account_avatar_file_size]),
        ),
    ]
