# Generated by Django 4.0 on 2023-02-25 21:12

import accounts.models
import accounts.validators
import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_contact_number_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_avatar.jpg', upload_to=accounts.models.Account.get_account_avatar_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), accounts.validators.validate_account_avatar_file_size]),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.CharField(help_text='Supported Formats: +8801757551134, 8801757871165 or 01715604232', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+?88)?01[3-9]\\d{8}$')]),
        ),
    ]
