# Generated by Django 4.0 on 2023-02-25 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Supported Formats: +8801757551134, 8801757871165 or 01715604232', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+?88)?01[3-9]\\d{8}$', message='Contact number must be entered in following formats: +8801757551134, 8801857871165 or 01915604232')]),
        ),
    ]
