# Generated by Django 4.0 on 2023-02-28 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_bio_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(help_text='Road/Village/Town/House Info', max_length=255)),
                ('district', models.CharField(help_text='District Name', max_length=100)),
                ('upazilla', models.CharField(help_text='Upazilla Name', max_length=100)),
                ('postal_code', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9350)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_address', to='accounts.account')),
            ],
        ),
    ]
