# Generated by Django 4.0 on 2023-03-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
