# Generated by Django 4.0 on 2023-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_first_name_account_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(help_text='Full Name', max_length=200),
        ),
    ]
