# Generated by Django 4.0 on 2023-03-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_full_name_account_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address_line',
        ),
    ]
