# Generated by Django 4.0 on 2023-02-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='University Name', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your Full Name', max_length=200)),
                ('email', models.EmailField(help_text='Your Email Address', max_length=60, verbose_name='email')),
                ('universiy', models.CharField(help_text='University Name', max_length=150)),
                ('review', models.TextField(help_text='Write your review', max_length=400)),
                ('rating', models.CharField(choices=[('1', 'ONE STAR'), ('2', 'TWO STAR'), ('3', 'THREE STAR'), ('4', 'FOUR STAR'), ('5', 'FIVE STAR')], default='THREE STAR', max_length=10)),
                ('is_verfied', models.BooleanField(default=False, help_text='Review is verified or not')),
                ('will_be_displayed', models.BooleanField(default=False, help_text='If this field is checked, Review will be displayed in website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who has reviewed the review', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
