# Generated by Django 4.0 on 2023-02-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('student_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='User who has reviewed the review', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='Review is checked by signals'),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='rating',
            field=models.CharField(choices=[('1', 'ONE STAR'), ('2', 'TWO STAR'), ('3', 'THREE STAR'), ('4', 'FOUR STAR'), ('5', 'FIVE STAR')], default='3', max_length=10),
        ),
    ]
