# Generated by Django 4.0 on 2023-02-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0002_remove_studentfeedback_verified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='edited_by',
            new_name='verified_by',
        ),
    ]
