# Generated by Django 4.0 on 2023-02-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0003_rename_edited_by_studentfeedback_verified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='is_verfied',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='universiy',
            new_name='university',
        ),
    ]
