# Generated by Django 4.0 on 2023-02-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0004_rename_is_verfied_studentfeedback_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='verified_by',
        ),
    ]
