# Generated by Django 4.0 on 2023-02-27 07:18

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import student_forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('student_forum', '0005_remove_studentfeedback_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name where student gets internship or placement', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Student Email Address', max_length=60, verbose_name='email')),
                ('student_bio', models.CharField(max_length=255)),
                ('card_image', imagekit.models.fields.ProcessedImageField(help_text='This image will be displayed in list view card', upload_to=student_forum.models.SuccessStory.get_success_story_card_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), student_forum.models.validate_success_story_card_image_file_size])),
                ('story_tagline', models.CharField(max_length=150)),
                ('story', ckeditor_uploader.fields.RichTextUploadingField(help_text='The success story', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='The company name where the student got internship or placement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_forum.company')),
                ('edited_by', models.ForeignKey(help_text='The person who create or edit the story', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('student', models.ForeignKey(help_text='The person who belongs to the story', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_story_holder', to='accounts.account')),
            ],
        ),
    ]
