# Generated by Django 4.0 on 2023-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0006_company_successstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='studentfeedback',
            options={'verbose_name': 'Student Feedback', 'verbose_name_plural': 'Student Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='successstory',
            name='card_intro',
            field=models.CharField(default='', help_text='This introduction will be displayed in list card', max_length=255),
        ),
    ]
