# Generated by Django 4.0 on 2023-02-27 07:59

import django.core.validators
from django.db import migrations
import imagekit.models.fields
import student_forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0007_alter_company_options_alter_studentfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='card_image',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in list view card', upload_to=student_forum.models.SuccessStory.get_success_story_card_image_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), student_forum.models.validate_success_story_card_image_file_size]),
        ),
    ]
