# Generated by Django 4.0 on 2023-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0008_alter_successstory_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='card_intro',
            field=models.CharField(help_text='This introduction will be displayed in list card', max_length=255),
        ),
    ]
