# Generated by Django 4.0 on 2023-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0009_alter_successstory_card_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='email',
        ),
        migrations.AlterField(
            model_name='successstory',
            name='student_bio',
            field=models.CharField(help_text='This bio will be displayed in sucess story page.', max_length=255),
        ),
    ]
