# Generated by Django 4.0 on 2023-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0010_remove_successstory_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='card_intro',
            field=models.TextField(help_text='This introduction will be displayed in list card', max_length=255),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='student_bio',
            field=models.TextField(help_text='This bio will be displayed in sucess story page.', max_length=255),
        ),
    ]
