# Generated by Django 4.0 on 2023-02-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('student_forum', '0011_alter_successstory_card_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='feedback_given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given_by', to='accounts.account'),
        ),
    ]
