# Generated by Django 4.0 on 2023-02-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_contact_number'),
        ('student_forum', '0012_studentfeedback_feedback_given_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='feedback_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given_by', to='accounts.account'),
        ),
    ]
