# Generated by Django 4.0 on 2023-02-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
        ('student_forum', '0014_delete_university_alter_studentfeedback_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CompanyInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, help_text='Any details you want to add...', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_internship', to='student_forum.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_internship', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Company Internship',
                'verbose_name_plural': 'Company Internship',
            },
        ),
    ]
