# Generated by Django 4.0 on 2023-02-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0015_studentfeedback_updated_at_companyinternship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyinternship',
            constraint=models.UniqueConstraint(fields=('company', 'student'), name='unique_company_internship'),
        ),
    ]
