# Generated by Django 4.0 on 2023-03-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
        ('student_forum', '0017_studentadmissiontransactioninfo_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=10, unique=True)),
                ('certificate', models.FileField(blank=True, help_text='certificate file', upload_to='')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The person who create the certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificate', to='accounts.account')),
            ],
        ),
    ]
