# Generated by Django 4.0 on 2023-03-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0018_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='university',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
