# Generated by Django 4.0 on 2023-03-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0019_remove_studentfeedback_university_delete_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='feedback_given_by',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='name',
        ),
    ]
