# Generated by Django 4.0 on 2023-03-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0020_remove_studentfeedback_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedback',
        ),
    ]
