# Generated by Django 4.0 on 2023-03-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0022_studentfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='verified_by',
        ),
    ]
