# Generated by Django 4.0 on 2023-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0023_remove_studentfeedback_verified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successstory',
            old_name='card_image',
            new_name='image_thumbnail',
        ),
    ]
