# Generated by Django 4.0 on 2023-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0024_rename_card_image_successstory_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
