# Generated by Django 4.0 on 2023-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0025_successstory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
