# Generated by Django 4.0 on 2023-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_forum', '0026_alter_successstory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
