# Generated by Django 4.0 on 2023-02-25 21:49

import ckeditor.fields
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import skills.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required: course name', max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
                ('total_duration', models.CharField(help_text='Required: course duration in hours/minutes or in weeks/months format', max_length=50)),
                ('title_intro', ckeditor.fields.RichTextField(help_text='Required: title introduction - maximum  3 to 4 lines', max_length=300)),
                ('what_you_will_learn', ckeditor_uploader.fields.RichTextUploadingField(help_text='Required: what you will learn content - maximum 1000 characters', max_length=1000)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Required: Long Description - maximum 3000 characters', max_length=3000)),
                ('preview_video', models.FileField(help_text='Required: course preview video. Supported file format: mp4. Maximum file limit:20mb', upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4']), skills.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(help_text='User who create or edit the course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='CourseChater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(help_text='Required:Chapter name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Required: Choose the course name.                                                   N.B: If you delete the course, related course chapters will be automatically deleted', on_delete=django.db.models.deletion.CASCADE, related_name='course_chapter', to='skills.course')),
                ('edited_by', models.ForeignKey(help_text='User who create or edit the course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
