# Generated by Django 4.0 on 2023-02-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_category_course_is_active_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursechater',
            old_name='chapter',
            new_name='chapter_name',
        ),
    ]
