# Generated by Django 4.0 on 2023-02-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_chapter_coursechater_chapter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(help_text='Required:Chapter name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Required: Choose the course name.                                                   N.B: If you delete the course, related course chapters will be automatically deleted', on_delete=django.db.models.deletion.CASCADE, related_name='course_chapter', to='skills.course')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseChater',
        ),
    ]
