# Generated by Django 4.0 on 2023-02-26 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import skills.validators


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_chapter_delete_coursechater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview_video',
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_file',
            field=models.FileField(blank=True, help_text='Required: course preview video. Supported file format: mp4. Maximum file limit:20mb', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4']), skills.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, default='', help_text='preview video url like youtube video url.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_category', to='skills.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Required: course name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='course safe URL'),
        ),
    ]
