# Generated by Django 4.0 on 2023-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_course_preview_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='preview video url like youtube video url.'),
        ),
    ]
