# Generated by Django 4.0 on 2023-02-26 19:14

import django.core.validators
from django.db import migrations, models
import skills.models
import skills.validators


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_course_is_active_freeresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_video_file',
            field=models.FileField(blank=True, help_text='Course preview video. Supported file format: mp4. Maximum file limit:20mb', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4']), skills.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='freeresources',
            name='resource_file',
            field=models.FileField(blank=True, help_text="Resource file.If you upload file,don't add resource_file url. Supported file format: pdf. Maximum file limit:20mb", null=True, upload_to=skills.models.FreeResources.get_resource_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), skills.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='freeresources',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Resource url or link. If you add url dont upload file.'),
        ),
    ]
