# Generated by Django 4.0 on 2023-02-27 15:14

import django.core.validators
from django.db import migrations
import imagekit.models.fields
import skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_course_preview_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default/default_card.jpg', help_text='This image will be displayed in list view card', upload_to=skills.models.Course.get_image_thumbnail_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), skills.models.validate_image_thumbnail_file_size]),
        ),
    ]
