# Generated by Django 4.0 on 2023-03-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_herosection_page_herosection_page_name'),
        ('skills', '0009_course_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_hero_section', to='core.herosection'),
        ),
    ]
