# Generated by Django 4.0 on 2023-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_learningitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningitem',
            options={'verbose_name': 'What You Wil Learn', 'verbose_name_plural': 'What You Wil Learn'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
