# Generated by Django 4.0 on 2023-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_alter_learningitem_options_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
