# Generated by Django 4.0 on 2023-03-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_lessions',
            field=models.CharField(blank=True, help_text='Required: Total number of lessions', max_length=50),
        ),
    ]
