# Generated by Django 4.0 on 2023-03-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_course_number_of_lessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningitem',
            old_name='item',
            new_name='point',
        ),
    ]
