# Generated by Django 4.0 on 2023-03-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_rename_item_learningitem_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number_of_lessions',
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_lectures',
            field=models.IntegerField(blank=True, help_text='Required: Total number of lessions', null=True),
        ),
    ]
