# Generated by Django 4.0 on 2023-02-28 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Degree Name Like: B.B.A, B.Sc. etc', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Graduation Exam Name',
                'verbose_name_plural': 'Graduation Exam Name',
            },
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Science, Commerce, Humanities etc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSCEquivalentExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Degree Name Like: H.S.c, A Level, Alim etc', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HSC\\Equivalent Exam',
                'verbose_name_plural': 'HSC\\Equivalent Exam',
            },
        ),
        migrations.CreateModel(
            name='PostGraduationExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Degree Name Like: B.B.A, B.Sc. etc', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSCEquivalentExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Degree Name Like: S.S.C, Dakhil. O Level etc', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSC\\Equivalent Exam',
                'verbose_name_plural': 'SSC\\Equivalent Exam',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject Name: Computer Eng. or Accounting etc', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='University or Institution Name', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='institution name', max_length=255)),
                ('gpa', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ssc_info', to='accounts.account')),
                ('exam', models.ForeignKey(help_text='examination type', on_delete=django.db.models.deletion.PROTECT, to='resume.sscequivalentexamname')),
                ('group', models.ForeignKey(help_text='GROUP Name', on_delete=django.db.models.deletion.PROTECT, to='resume.groupname')),
            ],
        ),
        migrations.CreateModel(
            name='PostGraduationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_year_student', models.CharField(max_length=20, verbose_name=(('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('Just Passed', 'Just Passed')))),
                ('cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.0)])),
                ('division', models.CharField(blank=True, choices=[('1st division', '1st division'), ('2nd division', '2nd division'), ('3rd division', '3rd division')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_post_grad_info', to='accounts.account')),
                ('exam', models.ForeignKey(help_text='examination type', on_delete=django.db.models.deletion.PROTECT, to='resume.postgraduationexamname')),
                ('subject', models.ForeignKey(help_text='subject name', on_delete=django.db.models.deletion.PROTECT, to='resume.subject')),
                ('university', models.ForeignKey(help_text='university_name', on_delete=django.db.models.deletion.PROTECT, related_name='university_post_graduate', to='resume.university')),
            ],
        ),
        migrations.CreateModel(
            name='HSCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='institution name', max_length=255)),
                ('gpa', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_hsc_info', to='accounts.account')),
                ('exam', models.ForeignKey(help_text='examination type', on_delete=django.db.models.deletion.PROTECT, to='resume.hscequivalentexamname')),
                ('group', models.ForeignKey(help_text='GROUP Name', on_delete=django.db.models.deletion.PROTECT, to='resume.groupname')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_year_student', models.CharField(max_length=20, verbose_name=(('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4rth Year', '4th Year'), ('Just Passed', 'Just Passed')))),
                ('result_type', models.CharField(choices=[('Grade', 'Grade'), ('Division', 'Division')], max_length=25)),
                ('cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.0)])),
                ('division', models.CharField(blank=True, choices=[('1st division', '1st division'), ('2nd division', '2nd division'), ('3rd division', '3rd division')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_grad_info', to='accounts.account')),
                ('exam', models.ForeignKey(help_text='examination type', on_delete=django.db.models.deletion.PROTECT, to='resume.graduationexamname')),
                ('subject', models.ForeignKey(help_text='subject name', on_delete=django.db.models.deletion.PROTECT, to='resume.subject')),
                ('university', models.ForeignKey(help_text='university_name', on_delete=django.db.models.deletion.PROTECT, related_name='university_graduate', to='resume.university')),
            ],
        ),
    ]
