# Generated by Django 4.0 on 2023-03-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, help_text='University or Institution Short Name', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentCurrentEducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(help_text='examination type', max_length=30)),
                ('which_year_student', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_current_edu_info', to='accounts.account')),
                ('subject', models.ForeignKey(help_text='subject name', on_delete=django.db.models.deletion.PROTECT, to='resume.subject')),
                ('university', models.ForeignKey(help_text='university_name', on_delete=django.db.models.deletion.PROTECT, related_name='student_current_university', to='resume.university')),
            ],
        ),
    ]
