# Generated by Django 4.0 on 2023-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_university_short_name_studentcurrenteducationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcurrenteducationinfo',
            name='university_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
