# Generated by Django 4.0 on 2023-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_studentcurrenteducationinfo_university_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcurrenteducationinfo',
            name='university_level',
            field=models.CharField(max_length=20),
        ),
    ]
