# Generated by Django 4.0 on 2023-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_studentcurrenteducationinfo_university_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationinfo',
            name='which_year_student',
            field=models.CharField(choices=[('first_year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4rth Year', '4th Year'), ('Just Passed', 'Just Passed')], max_length=20),
        ),
    ]
