# Generated by Django 4.0 on 2023-03-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_graduationinfo_result_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcurrenteducationinfo',
            old_name='exam',
            new_name='exam_name',
        ),
    ]
