# Generated by Django 4.0 on 2023-03-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_studentsperuniversityinfo_university'),
        ('student_forum', '0019_remove_studentfeedback_university_delete_certificate'),
        ('resume', '0008_rename_exam_studentcurrenteducationinfo_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='graduationinfo',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='graduationinfo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='graduationinfo',
            name='university',
        ),
        migrations.RemoveField(
            model_name='hscinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='hscinfo',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='hscinfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='postgraduationinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='postgraduationinfo',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='postgraduationinfo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='postgraduationinfo',
            name='university',
        ),
        migrations.RemoveField(
            model_name='sscinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sscinfo',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='sscinfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentcurrenteducationinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='studentcurrenteducationinfo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentcurrenteducationinfo',
            name='university',
        ),
        migrations.DeleteModel(
            name='GraduationExamName',
        ),
        migrations.DeleteModel(
            name='GraduationInfo',
        ),
        migrations.DeleteModel(
            name='GroupName',
        ),
        migrations.DeleteModel(
            name='HSCEquivalentExamName',
        ),
        migrations.DeleteModel(
            name='HSCInfo',
        ),
        migrations.DeleteModel(
            name='PostGraduationExamName',
        ),
        migrations.DeleteModel(
            name='PostGraduationInfo',
        ),
        migrations.DeleteModel(
            name='SSCEquivalentExamName',
        ),
        migrations.DeleteModel(
            name='SSCInfo',
        ),
        migrations.DeleteModel(
            name='StudentCurrentEducationInfo',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
